name: Build IUPAC mini-bundle

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure tools
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y unzip zip curl coreutils

      - name: Prepare folders
        run: |
          set -euxo pipefail
          rm -rf bundle work
          mkdir -p bundle work lib

      - name: Download + verify Maven jars (CDK 2.9)
        working-directory: work
        run: |
          set -euxo pipefail

          maven_dl() { # groupPath artifact version outname
            BASE="https://repo1.maven.org/maven2/$1/$2/$3/$2-$3.jar"
            SHA="${BASE}.sha1"
            echo "Downloading $BASE"
            curl -L --fail --retry 3 --retry-all-errors -o "$4" "$BASE"
            echo "Downloading checksum $SHA"
            curl -L --fail --retry 3 --retry-all-errors -o "$4.sha1" "$SHA"
            EXP=$(tr -d ' \n\r' < "$4.sha1")
            ACT=$(sha1sum "$4" | awk '{print $1}')
            if [ "$EXP" != "$ACT" ]; then
              echo "SHA1 mismatch for $4"
              echo "Expected: $EXP"
              echo "Actual:   $ACT"
              exit 1
            fi
            # quick zip test
            unzip -tq "$4"
          }

          maven_dl org/openscience/cdk cdk-interfaces 2.9 cdk-interfaces-2.9.jar
          maven_dl org/openscience/cdk cdk-core       2.9 cdk-core-2.9.jar
          maven_dl org/openscience/cdk cdk-smiles     2.9 cdk-smiles-2.9.jar
          maven_dl org/openscience/cdk cdk-dict       2.9 cdk-dict-2.9.jar

      - name: Download Ambit 3.0.0 jars (SourceForge) + zip test
        working-directory: work
        run: |
          set -euxo pipefail
          dl() {
            echo "Downloading $1"
            curl -L --fail --retry 3 --retry-all-errors -o "$2" "$1"
            unzip -tq "$2"
          }
          # structure→name + dependencies
          dl "https://downloads.sourceforge.net/project/ambit/Ambit2/AMBIT_modules/3.0.0/ambit2-structure2name-3.0.0.jar" ambit2-structure2name-3.0.0.jar
          dl "https://downloads.sourceforge.net/project/ambit/Ambit2/AMBIT_modules/3.0.0/ambit2-core-3.0.0.jar"            ambit2-core-3.0.0.jar
          dl "https://downloads.sourceforge.net/project/ambit/Ambit2/AMBIT_modules/3.0.0/ambit2-smarts-3.0.0.jar"          ambit2-smarts-3.0.0.jar

      - name: Unpack all jars into bundle/
        run: |
          set -euxo pipefail
          shopt -s nullglob
          # Extract with overwrite (-o) and quiet (-q) to avoid prompts
          for J in work/*.jar; do
            echo "Unzipping $J"
            unzip -oq "$J" -d bundle
          done
          # Remove signature files (avoid security metadata conflicts)
          find bundle -type f \( -name "*.SF" -o -name "*.DSA" -o -name "*.RSA" \) -delete
          # Optional: remove all MANIFEST.MF so we don't mix multiple manifests
          find bundle -type f -name MANIFEST.MF -delete

      - name: Build combined JAR
        run: |
          set -euxo pipefail
          cd bundle
          zip -qr ../lib/iupac-mini-bundle.jar .
          cd ..
          ls -lh lib/iupac-mini-bundle.jar
          BYTES=$(stat -c%s lib/iupac-mini-bundle.jar || stat -f%z lib/iupac-mini-bundle.jar || echo 0)
          echo "Bundle size: $BYTES bytes"
          if [ "$BYTES" -gt $((25*1024*1024)) ]; then
            echo "ERROR: iupac-mini-bundle.jar exceeds 25 MiB (GitHub Pages limit)."
            exit 1
          fi

      - name: Upload bundle as artifact
        uses: actions/upload-artifact@v4
        with:
          name: iupac-mini-bundle.jar
          path: lib/iupac-mini-bundle.jar
          if-no-files-found: error

      - name: Commit mini-bundle into repo
        run: |
          set -euxo pipefail
          if [ -n "$(git status --porcelain lib/iupac-mini-bundle.jar)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add lib/iupac-mini-bundle.jar
            git commit -m "Add/update iupac-mini-bundle.jar (CDK 2.9 + Ambit 3.0.0)"
            git push
          else
            echo "No changes to commit."
          fi
